### ISSUE TITLE
crash with some files to download

### ISSUE THREAD

**Issue by phoretis** [vlacour97/alldebrid-watcher#33]
Hi,

Thanks for your program, it's really useful !

I recently realized that it could crash when adding a torrent file to the monitored folder.
First question, the windows cmd closes without showing the error message. How do I activate the logs ?
There are some in the “C:\Users\xxxx\AppData\Local\npm-cache” folder, but they are almost empty.

After several tests, the torrent downloads a file with a “|” in its name, which is impossible, so the crash probably came from there.

Thanks in advance for your help

**Comment by Ant4r** [comment]
I have a lot of issue like this. Often the application crash ( i use it in docker).
Here the logs of the error : 
```
The file "Blue Mountain State - S03E13.mp4" has been debrided on your server
/app/src/notifier/stdout-notifier.ts:26
        process.stdout.clearLine(0);
                       ^
TypeError: process.stdout.clearLine is not a function
    at StdoutNotifier.notifyOnDownloadProgress (/app/src/notifier/stdout-notifier.ts:26:24)
    at NotifierStrategy.notifyOnDownloadProgress (/app/src/notifier/notifier-strategy.ts:81:58)
    at DownloadFile.<anonymous> (/app/src/kernel.ts:91:89)
    at EventEmitter.<anonymous> (/app/src/file/download-file.ts:39:59)
    at EventEmitter.emit (node:events:512:28)
    at EventEmitter.emit (node:domain:489:12)
    at Request.<anonymous> (/app/src/downloader/filesystem-downloader.ts:66:30)
    at Request.emit (node:events:512:28)
    at Request.emit (node:domain:489:12)
    at reportState (/app/node_modules/request-progress/index.js:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
